services:
  evolution-api:
    image: atendai/evolution-api:v2.2.3
    container_name: evolution-botimperio
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: imperio2025api
      SERVER_URL: http://localhost:8080
      DEL_INSTANCE: false
      WEBHOOK_GLOBAL_ENABLED: false
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
