services:
  - type: web
    name: evolution-botimperio
    runtime: image
    plan: free
    image:
      url: docker.io/atendai/evolution-api:v2.1.1
    healthCheckPath: /
    envVars:
      - key: AUTHENTICATION_API_KEY
        value: imperio2025api
      - key: DEL_INSTANCE
        value: "false"
      - key: SERVER_URL
        sync: false
      - key: SERVER_PORT
        value: "10000"
      - key: DATABASE_ENABLED
        value: "false"
      - key: CACHE_REDIS_ENABLED
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "true"
